microsoftteamsnew)
      appTitle="Microsoft Teams"
      appFiles+=("/Applications/Microsoft Teams classic.app")
      appFiles+=("/Applications/Microsoft Teams.app")
      appFiles+=("<<Users>>/Library/Application Scripts/com.microsoft.teams2")
      appFiles+=("<<Users>>/Library/Application Scripts/com.microsoft.teams2.notificationcenter")
      appFiles+=("<<Users>>/Library/Containers/com.microsoft.teams2")
      appFiles+=("<<Users>>/Library/Containers/com.microsoft.teams2.notificationcenter")
      appFiles+=("<<Users>>/Library/WebKit/com.microsoft.teams2")
      appFiles+=("<<Users>>/Library/Saved Application State/com.microsoft.teams2.savedState")
      appFiles+=("<<Users>>/Library/Preferences/com.microsoft.teams2.plist ")
      appFiles+=("<<Users>>/Library/HTTPStorages/com.microsoft.teams2.binarycookies")
      appFiles+=("<<Users>>/Library/HTTPStorages/com.microsoft.teams2")
      appFiles+=("<<Users>>/Library/Group Containers/UBF8T346G9.com.microsoft.teams2")
      appFiles+=("<<Users>>/Library/Caches/com.microsoft.teams2")
      appFiles+=("<<Users>>/Library/Preferences/com.microsoft.teams2.helper.plist")
      appFiles+=("<<Users>>/Library/Saved Application State/com.microsoft.teams2.savedState")
      appFiles+=("/var/db/receipts/com.microsoft.teams2.born")
      appLaunchDaemons+=("/Library/LaunchDaemons/com.microsoft.teams2.TeamsUpdaterDaemon.plist")
      preflightCommand+=("killall 'Teams'")
      ;;
